# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2e844c51136435113ea31aaa1ed35486dbe6f63c42152f97dbe4c25d8b1b39efdffa65fefef394cad3b6e60ee6f919b8ba5d5c45bcd75f677ff2c2c60ce5297

test:
  secret_key_base: 6f30af4ccf14193a589b0c46b859a7b3b63e0da67a083caa02c3c6bce4ee2d12e5bea00e1d8698fe6391555531bd4c87fd21ca2075eadb78537223f76d26ae87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
